sudo: required
services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t packebian/frontend:latest .
  - docker tag packebian/frontend:latest packebian/frontend:stable

script:
  - echo "No tests yet"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push packebian/frontend:stable ;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker push packebian/frontend:latest ;
    fi

branches:
  only:
    - master
    - develop
